language: python
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - nginx
            - apache2
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
    -  SERVER=nginx
    -  SERVER=apache
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: tests/run-travis.sh
